### ISSUE TITLE
“Input the ImageNet pre-trained network: ”   What should I input?

### ISSUE THREAD

**Issue by wang66624** [asmaa4may/DeTraC_COVId19#10]
![image](https://user-images.githubusercontent.com/81811919/168464721-dd11e33e-88e9-4dae-8458-42df5de11b4a.png)

**Comment by asmaa4may** [comment]
Dear sir,
In this image, the If statement was used to call the pre-trained ImageNet. SeriesNetwork for Alexnet e.g and DAGNetwork for google Net, Resnet pretrained networks. If you need anything else, please let me know.

Regards,
Asmaa


Asmaa Abbas Hassan
***@***.***
Assiut University, Egypt

________________________________
From: wang66624 ***@***.***>
Sent: Sunday, May 15, 2022 10:49 AM
To: asmaa4may/DeTraC_COVId19 ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [asmaa4may/DeTraC_COVId19] “Input the ImageNet pre-trained network: ” What should I input? (Issue #10)


[image]<https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fuser-images.githubusercontent.com%2F81811919%2F168464721-dd11e33e-88e9-4dae-8458-42df5de11b4a.png&data=05%7C01%7Casmaa.abbas%40science.aun.edu.eg%7C7d1826d5efe94bf4c28308da364fc7be%7C794544284dbe401ab2ab64a5a7069e2b%7C1%7C0%7C637882013527107760%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=s5Ah3AYTp9oXjvUSkV899TNVCq9YvQmyjhuMhIKa4OA%3D&reserved=0>

**Comment by asmaa4may** [comment]
What should I input?
A pre-trained ImageNet for transfer learning.
