### ISSUE TITLE
There is no file that names "Training_after_decompose.m"

### ISSUE THREAD

**Issue by wang66624** [asmaa4may/DeTraC_COVId19#11]
![image](https://user-images.githubusercontent.com/81811919/168465711-d51a123c-6c99-47f7-a2ba-9d3c6b835a2e.png)

**Comment by asmaa4may** [comment]
Dear sir,
In the last line, you need to run the same code but on the dataset B (the decomposed classes). I suggest you reading the original paper. "DeTraC: Transfer Learning of Class Decomposed Medical Images in Convolutional Neural Networks".
or you can follow the steps in the algorithm.

Asmaa Abbas Hassan
***@***.***
Assiut University, Egypt
________________________________
From: wang66624 ***@***.***>
Sent: Sunday, May 15, 2022 11:16 AM
To: asmaa4may/DeTraC_COVId19 ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [asmaa4may/DeTraC_COVId19] There is no file that names "Training_after_decompose.m" (Issue #11)


[image]<https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fuser-images.githubusercontent.com%2F81811919%2F168465711-d51a123c-6c99-47f7-a2ba-9d3c6b835a2e.png&data=05%7C01%7Casmaa.abbas%40science.aun.edu.eg%7Cc56e5693c0f34e43781308da3653a6d1%7C794544284dbe401ab2ab64a5a7069e2b%7C1%7C0%7C637882030156385797%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=uIQttlCncL6sz8eaAmps1XBG8i5mYsI16bc%2BRiRkV8w%3D&reserved=0>
